/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class FrmFastSnackMenuPral extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFastSnackMenuPral.class.getName());

    /**
     * Creates new form FrmFastSnackMenuPral
     */
    public FrmFastSnackMenuPral() {
        initComponents();

        txtNombre.requestFocus();
        txtFecha.setText(
                new java.text.SimpleDateFormat("dd/MM/yyyy")
                        .format(new java.util.Date()));
        txtFecha.setEditable(false);
        txtFecha.setEditable(false);
        txtTotalPedido.setEditable(false);
        txtFactura.setEditable(false);
        txtFactura.setText(String.valueOf((int) (Math.random() * 10000)));

    }

    public void BorrarCampos() {

        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtFactura.setText("");
        txtFecha.setText("");
        Cedula.setText("");
        txtBanco.setText("");
        txtTotalPedido.setText("");

        cmbMetodopago.setSelectedIndex(0);
        txtNombre.requestFocus();
    }

    public javax.swing.JTextField getTxtTotalPedido() {
        return txtTotalPedido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textNFactura = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        textCiente = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        textFecha = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMetodopago = new javax.swing.JComboBox<>();
        Direccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        Banco = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPedido = new javax.swing.JTextField();
        btnGuardarPedido = new javax.swing.JButton();
        btnBorrarPedido = new javax.swing.JButton();
        btnNuevoPedido = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        chkConsumidorFinal = new java.awt.Checkbox();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Tu antojo, más rápido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 180, -1));

        textNFactura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textNFactura.setText("N° Factura:");
        getContentPane().add(textNFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtFactura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFactura.addActionListener(this::txtFacturaActionPerformed);
        getContentPane().add(txtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 125, -1));

        textCiente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textCiente.setText("Nombre:");
        getContentPane().add(textCiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, -1));

        txtFecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFecha.addActionListener(this::txtFechaActionPerformed);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 136, -1));

        textFecha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textFecha.setText("Fecha:");
        getContentPane().add(textFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        Telefono.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Telefono.setText("Teléfono:");
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 188, -1));

        Cedula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cedula.setText("Cédula:");
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        txtCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCedula.addActionListener(this::txtCedulaActionPerformed);
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 183, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logotipo.jpeg"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 280, 100));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Metodo de Pago:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 326, -1, -1));

        cmbMetodopago.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbMetodopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Efectivo", "Tarjeta de Débito ", "Tarjeta de Crédito", "Transferencia Bancaria" }));
        cmbMetodopago.addActionListener(this::cmbMetodopagoActionPerformed);
        getContentPane().add(cmbMetodopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 349, 135, -1));

        Direccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Direccion.setText("Dirección:");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 229, -1));

        Banco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Banco.setText("Banco:");
        getContentPane().add(Banco, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 326, -1, -1));

        txtBanco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtBanco.addActionListener(this::txtBancoActionPerformed);
        getContentPane().add(txtBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 349, 120, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Total:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        txtTotalPedido.setBackground(new java.awt.Color(255, 204, 153));
        txtTotalPedido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalPedido.addActionListener(this::txtTotalPedidoActionPerformed);
        getContentPane().add(txtTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 130, -1));

        btnGuardarPedido.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardarPedido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnGuardarPedido.setText("Confirmar Pedido");
        btnGuardarPedido.addActionListener(this::btnGuardarPedidoActionPerformed);
        getContentPane().add(btnGuardarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        btnBorrarPedido.setBackground(new java.awt.Color(255, 102, 102));
        btnBorrarPedido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBorrarPedido.setText("Borrar Pedido");
        btnBorrarPedido.addActionListener(this::btnBorrarPedidoActionPerformed);
        getContentPane().add(btnBorrarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        btnNuevoPedido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNuevoPedido.setText("Nuevo Pedido");
        btnNuevoPedido.addActionListener(this::btnNuevoPedidoActionPerformed);
        getContentPane().add(btnNuevoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Comida rapida-FS.jpeg"))); // NOI18N
        jLabel6.setText("jLabel3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 264, 202));

        chkConsumidorFinal.setBackground(new java.awt.Color(255, 204, 102));
        chkConsumidorFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chkConsumidorFinal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chkConsumidorFinal.setLabel("Consumidor Final");
        chkConsumidorFinal.addItemListener(this::chkConsumidorFinalItemStateChanged);
        getContentPane().add(chkConsumidorFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jButton1.setText("Buscar 🔍");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jMenu1.setText("Menú");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Regresar al Inicio");
        jCheckBoxMenuItem1.addActionListener(this::jCheckBoxMenuItem1ActionPerformed);
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMetodopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodopagoActionPerformed
        if (cmbMetodopago.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un método de pago");
            return;
        }
    }//GEN-LAST:event_cmbMetodopagoActionPerformed
    private boolean esConsumidorFinal = false;
    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed
        if (!esConsumidorFinal) {
            if (txtNombre.getText().trim().isEmpty()
                    || txtTelefono.getText().trim().isEmpty()
                    || txtCedula.getText().trim().isEmpty()
                    || txtDireccion.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Debe completar todos los datos del cliente"
                );
                return;
            }
        }

        FrmPedidoExitoso exito = new FrmPedidoExitoso();

        exito.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void btnBorrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPedidoActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(
                null,
                "¿Desea borrar todos los datos?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            BorrarCampos();
        }
    }//GEN-LAST:event_btnBorrarPedidoActionPerformed

    private void txtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPedidoActionPerformed
        BorrarCampos();
    }//GEN-LAST:event_btnNuevoPedidoActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        FrmInicio inicio = new FrmInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void txtTotalPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPedidoActionPerformed

    private void txtBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoActionPerformed
        String metodo = cmbMetodopago.getSelectedItem().toString();

        if (metodo.equals("Transferencia Bancaria")
                || metodo.equals("Tarjeta de Débito")
                || metodo.equals("Tarjeta de Crédito")) {

            txtBanco.setEnabled(true);

        } else {
            txtBanco.setText("No aplica");
            txtBanco.setEnabled(false);
        }
    }//GEN-LAST:event_txtBancoActionPerformed

    private void chkConsumidorFinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkConsumidorFinalItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            txtNombre.setText("Consumidor Final");
            txtCedula.setText("9999999999");
            txtNombre.setEditable(false);
            txtCedula.setEditable(false);
            txtTelefono.setText("----");
            txtBanco.setText("Efectivo");

            txtDireccion.requestFocus();

        } else {
            txtNombre.setText("");
            txtCedula.setText("");
            txtNombre.setEditable(true);
            txtCedula.setEditable(true);
        }
    }//GEN-LAST:event_chkConsumidorFinalItemStateChanged

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmFastSnackMenuPral().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banco;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton btnBorrarPedido;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnNuevoPedido;
    private java.awt.Checkbox chkConsumidorFinal;
    private javax.swing.JComboBox<String> cmbMetodopago;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel textCiente;
    private javax.swing.JLabel textFecha;
    private javax.swing.JLabel textNFactura;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotalPedido;
    // End of variables declaration//GEN-END:variables
}
