/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DAO.DetallePedidoDAO;
import DAO.PedidoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.DetallePedido;
import modelos.EstadoPedido;
import modelos.Pedido;
import modelos.Producto;

/**
 *
 * @author User
 */
public class FrmProductoPedido extends javax.swing.JFrame {

    FrmFastSnackMenuPral menu;

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(FrmProductoPedido.class.getName());

    DefaultTableModel modelo = new DefaultTableModel();

    double total = 0;

    /**
     *
     * Creates new form FrmProductoPedido
     */
    public FrmProductoPedido() {
        initComponents();
        configurarTabla();

    }

    private void configurarTabla() {
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Subtotal");

        tblCarrito.setModel(modelo);
    }

    public FrmProductoPedido(FrmFastSnackMenuPral menu) {
        initComponents();
        configurarTabla();
        this.menu = menu;
    }

    public void calcularTotal() {
        double total = 0;

        for (int i = 0; i < tblCarrito.getRowCount(); i++) {
            total += Double.parseDouble(tblCarrito.getValueAt(i, 4).toString());
        }
        txtTotalPedido.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        spnHotdog = new javax.swing.JSpinner();
        Hotdog = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        spnChuzo = new javax.swing.JSpinner();
        Chuzo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        spnChoclo = new javax.swing.JSpinner();
        Choclo = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        spnHamburguesa = new javax.swing.JSpinner();
        Hamburguesa = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        spnPapipollo = new javax.swing.JSpinner();
        Papipollo = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        spnSalchipapa = new javax.swing.JSpinner();
        Agregar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        spnCola = new javax.swing.JSpinner();
        Cola = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cmbCola = new javax.swing.JComboBox<>();
        spnJugo = new javax.swing.JSpinner();
        Jugo = new javax.swing.JButton();
        cmbJugo = new javax.swing.JComboBox<>();
        spnAgua = new javax.swing.JSpinner();
        Agua = new javax.swing.JButton();
        cmbAgua = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JLabel();
        txtTotalPedido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Bebidas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sapchipapa.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papipollo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hamburguesa.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hotdog.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chuzo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/choclo_150x89.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Hot-Dog");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("$2.00");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        spnHotdog.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnHotdog.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnHotdog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        Hotdog.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Hotdog.setText("Agregar");
        Hotdog.addActionListener(this::HotdogActionPerformed);
        getContentPane().add(Hotdog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Chuzo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("$1.00");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        spnChuzo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnChuzo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnChuzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        Chuzo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Chuzo.setText("Agregar");
        Chuzo.addActionListener(this::ChuzoActionPerformed);
        getContentPane().add(Chuzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Choclo");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("$1.50");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));

        spnChoclo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnChoclo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnChoclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, -1, -1));

        Choclo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Choclo.setText("Agregar");
        Choclo.addActionListener(this::ChocloActionPerformed);
        getContentPane().add(Choclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Hamburguesa");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("$3.50");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        spnHamburguesa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnHamburguesa.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        Hamburguesa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Hamburguesa.setText("Agregar");
        Hamburguesa.addActionListener(this::HamburguesaActionPerformed);
        getContentPane().add(Hamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Papipollo");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("$2.50");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        spnPapipollo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnPapipollo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnPapipollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        Papipollo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Papipollo.setText("Agregar");
        Papipollo.addActionListener(this::PapipolloActionPerformed);
        getContentPane().add(Papipollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Salchipapa");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("$2.50");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        spnSalchipapa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnSalchipapa.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        spnSalchipapa.setToolTipText("");
        getContentPane().add(spnSalchipapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        Agregar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(this::AgregarActionPerformed);
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Productos:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cola.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agua.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Cola");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, -1));

        spnCola.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnCola.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        Cola.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cola.setText("Agregar");
        Cola.addActionListener(this::ColaActionPerformed);
        getContentPane().add(Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Jugos");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Agua");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 220, -1, -1));

        cmbCola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca Cola", "Pepsi", "Sprite", "Fanta", "Coca Cola sin azucar" }));
        getContentPane().add(cmbCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 140, -1));

        spnJugo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnJugo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, -1, -1));

        Jugo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Jugo.setText("Agregar");
        Jugo.addActionListener(this::JugoActionPerformed);
        getContentPane().add(Jugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, -1, -1));

        cmbJugo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugo de Naranja", "Jugo de Limón", "Jugo de Piña", "Jugo de Maracuyá" }));
        getContentPane().add(cmbJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 140, -1));

        spnAgua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnAgua.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        getContentPane().add(spnAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 280, -1, -1));

        Agua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Agua.setText("Agregar");
        Agua.addActionListener(this::AguaActionPerformed);
        getContentPane().add(Agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 280, -1, -1));

        cmbAgua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua Natural", "Agua Mineral", "Agua con Gas" }));
        getContentPane().add(cmbAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 250, 140, -1));

        txtTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTotal.setText("Total:");
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, -1, -1));

        txtTotalPedido.setColumns(10);
        txtTotalPedido.addActionListener(this::txtTotalPedidoActionPerformed);
        getContentPane().add(txtTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Eliminar Pedido");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, -1, -1));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 990, -1, 70));

        jButton3.setBackground(new java.awt.Color(204, 255, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Confirmar Pedido");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 560, -1, 30));

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 600, 140));

        jScrollPane2.setViewportView(jScrollPane3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 700, 20));
        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 20, 620));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugos.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setText("FastSnack - Pedido");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 23, -1, -1));

        jMenu1.setText("Menú");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Regresar al Inicio");
        jCheckBoxMenuItem1.addActionListener(this::jCheckBoxMenuItem1ActionPerformed);
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HotdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotdogActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnHotdog.getValue();
        double precio = 2.50;
        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            "Hotdog", cantidad, precio, subtotal
        });

        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_HotdogActionPerformed

    private void ChuzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuzoActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnChuzo.getValue();
        double precio = 2.50;
        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            "Chuzo", cantidad, precio, subtotal
        });

        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_ChuzoActionPerformed

    private void ChocloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocloActionPerformed
        int cantidad = (Integer) spnChoclo.getValue();
        double precio = 1.50;
        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            "Choclo", cantidad, precio, subtotal
        });

        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_ChocloActionPerformed

    private void HamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamburguesaActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnHamburguesa.getValue();
        double precio = 3.50;
        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            "Hamburguesa", cantidad, precio, subtotal
        });

        txtTotalPedido.setText(
                String.valueOf(total));
    }//GEN-LAST:event_HamburguesaActionPerformed

    private void PapipolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapipolloActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnPapipollo.getValue();
        double precio = 2.50;
        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            "Papipollo", cantidad, precio, subtotal
        });

        txtTotalPedido.setText(
                String.valueOf(total));
    }//GEN-LAST:event_PapipolloActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnSalchipapa.getValue();
        double precio = 2.50;
        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            "Salchipapa", cantidad, precio, subtotal
        });

        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_AgregarActionPerformed

    private void ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnCola.getValue();

        String bebida = cmbCola.getSelectedItem().toString();

        if (bebida.equals("Ninguno")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione una bebida");

            return;
        }
        double precio = 1.00;

        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            bebida,
            cantidad,
            precio,
            subtotal
        });
        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_ColaActionPerformed

    private void JugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugoActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnJugo.getValue();

        String bebida = cmbJugo.getSelectedItem().toString();

        if (bebida.equals("Ninguno")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione una bebida");

            return;
        }
        double precio = 1.00;

        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            bebida,
            cantidad,
            precio,
            subtotal
        });
        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_JugoActionPerformed

    private void AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguaActionPerformed
        // TODO add your handling code here:
        int cantidad = (Integer) spnAgua.getValue();

        String bebida = cmbAgua.getSelectedItem().toString();

        if (bebida.equals("Ninguno")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione una bebida");

            return;
        }
        double precio = 1.00;

        double subtotal = cantidad * precio;
        total = total + subtotal;
        modelo.addRow(new Object[]{
            bebida,
            cantidad,
            precio,
            subtotal
        });
        txtTotalPedido.setText(
                String.valueOf(total));
        calcularTotal();
    }//GEN-LAST:event_AguaActionPerformed

    private void txtTotalPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPedidoActionPerformed


    }//GEN-LAST:event_txtTotalPedidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila = tblCarrito.getSelectedRow();

        if (fila >= 0) {

            double subtotal = Double.parseDouble(
                    tblCarrito.getValueAt(fila, 3).toString());

            double total = Double.parseDouble(
                    txtTotalPedido.getText());

            total = total - subtotal;

            txtTotalPedido.setText(String.valueOf(total));

            modelo.removeRow(fila);
            calcularTotal();
        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione una fila");
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PedidoDAO pedidoDAO = new PedidoDAO();
            DetallePedidoDAO detalleDAO = new DetallePedidoDAO();
            //ID cliente (AJUSTA si lo tienes en otro lado)
            int idCliente = 1; // o seleccionado desde otro formulario

            //Total del pedido
            double total = Double.parseDouble(txtTotalPedido.getText());
            //Crear pedido y obtener ID
            Pedido pedido = new Pedido();
            pedido.setCliente(new Cliente());
            pedido.getCliente().setIdCliente(idCliente);
            pedido.setTotal(total);
            pedido.setFecha(new java.util.Date());

            pedido.setEstado(EstadoPedido.PENDIENTE);

            int idPedido = pedidoDAO.guardarPedido(pedido);
            if (idPedido == -1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error al crear pedido");
                return;
            }
            //GUARDAR DETALLES SEGÚN SPINNERS
            if ((int) spnHotdog.getValue() > 0) {
                detalleDAO.guardarDetalle(
                        idPedido,
                        2, // id_producto Hotdog (según tu BD)
                        (int) spnHotdog.getValue(),
                        2.50
                );
            }
            if ((int) spnChuzo.getValue() > 0) {
                detalleDAO.guardarDetalle(
                        idPedido,
                        3, // Chuzo
                        (int) spnChuzo.getValue(),
                        2.50
                );
            }
            if ((int) spnHamburguesa.getValue() > 0) {
                detalleDAO.guardarDetalle(
                        idPedido,
                        1, // Hamburguesa
                        (int) spnHamburguesa.getValue(),
                        5.50
                );
            }
            javax.swing.JOptionPane.showMessageDialog(null, "Pedido confirmado correctamente");
            FrmFastSnackMenuPral menu = new FrmFastSnackMenuPral();
            menu.getTxtTotalPedido().setText(
                    String.valueOf(total));
            menu.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar su Pedido");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        FrmInicio inicio = new FrmInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProductoPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Agua;
    private javax.swing.JButton Choclo;
    private javax.swing.JButton Chuzo;
    private javax.swing.JButton Cola;
    private javax.swing.JButton Hamburguesa;
    private javax.swing.JButton Hotdog;
    private javax.swing.JButton Jugo;
    private javax.swing.JButton Papipollo;
    private javax.swing.JComboBox<String> cmbAgua;
    private javax.swing.JComboBox<String> cmbCola;
    private javax.swing.JComboBox<String> cmbJugo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spnAgua;
    private javax.swing.JSpinner spnChoclo;
    private javax.swing.JSpinner spnChuzo;
    private javax.swing.JSpinner spnCola;
    private javax.swing.JSpinner spnHamburguesa;
    private javax.swing.JSpinner spnHotdog;
    private javax.swing.JSpinner spnJugo;
    private javax.swing.JSpinner spnPapipollo;
    private javax.swing.JSpinner spnSalchipapa;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txtTotalPedido;
    // End of variables declaration//GEN-END:variables
}
